CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) ,
  password VARCHAR(255) ,
  image VARCHAR(255) ,
  googleId VARCHAR(255) ,
  isAuthenticated BOOLEAN DEFAULT FALSE
);